# Generated by Django 3.0.7 on 2020-09-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=20000)),
                ('label', models.BooleanField()),
            ],
        ),
    ]
